### ISSUE TITLE
哥们你好，我现在用的是2.3版本的，他没有‘from mmdet.datasets import (build_dataset, replace_ImageToTensor)’这个模块

### ISSUE THREAD

**Issue by yehaizi1995** [xuhuasheng/mmdetection_plot_pr_curve#1]
请问该如何处理呢

**Comment by xuhuasheng** [comment]
'replace_ImageToTensor'  can be removed since it is not used.
my mmdet's version is 2.4.0，the path of module 'build_dataset' may be changed，you can global search this module name.

**Comment by yehaizi1995** [comment]
OK .i have solved this problem,thankfully!




            
            
                
                    
                            
                                
                            
                            
                                1214098961
                            
                    
                        
                            
                                    邮箱：1214098961@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


在2020年12月25日 10:19，Watson 写道： 
'replace_ImageToTensor'  can be removed since it is not used.

my mmdet's version is 2.4.0，the path of module 'build_dataset' may be changed，you can global search this module name.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/xuhuasheng/mmdetection_plot_pr_curve/issues/1#issuecomment-751148995",
"url": "https://github.com/xuhuasheng/mmdetection_plot_pr_curve/issues/1#issuecomment-751148995",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
